/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package connect.me;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Krishan
 */
public class log_in extends javax.swing.JFrame {

    /**
     * Creates new form log_in
     */
    public log_in() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        txtupass = new javax.swing.JTextField();
        butsignin = new javax.swing.JButton();
        butlogin = new javax.swing.JButton();
        butexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl1.setText("Welcome to ConnectMe");

        lbl2.setText("Login in here!");

        lbl3.setText("User Name");

        lbl4.setText("Password");

        butsignin.setText("Sign-in");
        butsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butsigninActionPerformed(evt);
            }
        });

        butlogin.setText("Login");
        butlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butloginActionPerformed(evt);
            }
        });

        butexit.setText("Exit");
        butexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lbl1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(butsignin)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtuname)
                                .addComponent(txtupass, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butlogin)
                                .addGap(36, 36, 36)
                                .addComponent(butexit)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtuname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtupass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butsignin)
                    .addComponent(butlogin)
                    .addComponent(butexit))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butsigninActionPerformed
sign_in tonewsignin=new sign_in();
tonewsignin.setVisible(true);
dispose();        
    }//GEN-LAST:event_butsigninActionPerformed

    private void butloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butloginActionPerformed
      String un = txtuname.getText().trim();
        String pw = txtupass.getText().trim();

//Hard code user.

    {   
        // check from the file
        String filePath = "loginInfo.txt";        
        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) 
        {
            LoginInfo whois=new LoginInfo();
            String line;
            
            String username = null, password = null, role = null;

            boolean isValidLogin = false;
            
            while ((line = br.readLine()) != null) 
            {
                if (line.contains("Login Name :")) 
                {
                    username = line.split(":")[1].trim();
                } 
                else if (line.contains("Password :")) 
                {
                    password = line.split(":")[1].trim();
                } 
                else if (line.contains("Role :")) 
                {
                    role = line.split(":")[1].trim();
                }
                if (username != null && password != null && role != null) 
                {
                    if (username.equals(un)) 
                    {
                        if (password.equals(pw)) 
                        {
                            isValidLogin = true;
                            if (role.equals("HR Assistant")) 
                            {
                                HR_Assistant_Dashboard tohrAssistant = new HR_Assistant_Dashboard();
                                tohrAssistant.setVisible(true);
                                LoginInfo.Luser="HR Assistant";
                                dispose();
                            } 
                            else if (role.equals("HR Manager")) 
                            {
                                HR_Manager_Dashboard tohrmanager = new HR_Manager_Dashboard();
                                tohrmanager.setVisible(true);
                                LoginInfo.Luser="HR Manager";
                                dispose();
                            }
                            break; 
                        } 
                        else 
                        {
                            break; 
                        }
                    }
                    // Reset the variables for the next user
                    username = password = role = null;
                }
            }
            // Show error message if no valid login found
            if (!isValidLogin) 
            {
                JOptionPane.showMessageDialog(null, "Incorrect User Name or Password", "Login Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(IOException ex)
        {
                JOptionPane.showMessageDialog(null, "Login File Issue", "Login Error", JOptionPane.ERROR_MESSAGE);
        }
    }  // TODO add your handling code here:
    }//GEN-LAST:event_butloginActionPerformed

    private void butexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butexitActionPerformed
int response = JOptionPane.showConfirmDialog(null, "Do you want to continue?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if(response==JOptionPane.YES_OPTION)
        {        
            System.exit(0);
        }
        else
        {
        JOptionPane.showConfirmDialog(null, "You will stay here!!", "Stay", JOptionPane.OK_OPTION);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_butexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new log_in().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butexit;
    private javax.swing.JButton butlogin;
    private javax.swing.JButton butsignin;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JTextField txtuname;
    private javax.swing.JTextField txtupass;
    // End of variables declaration//GEN-END:variables
}
